#!/bin/bash

# PgBouncer Setup Script for ArtiConnect
# This script sets up PgBouncer for database connection pooling

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== ArtiConnect PgBouncer Setup ==="
echo ""

# Check if required environment variables are set
check_env_vars() {
    local missing=""

    [ -z "$DB_HOST" ] && missing="$missing DB_HOST"
    [ -z "$DB_NAME" ] && missing="$missing DB_NAME"
    [ -z "$DB_USER" ] && missing="$missing DB_USER"
    [ -z "$DB_PASSWORD" ] && missing="$missing DB_PASSWORD"

    if [ -n "$missing" ]; then
        echo "Error: Missing required environment variables:$missing"
        echo ""
        echo "Please set the following environment variables:"
        echo "  export DB_HOST=your-database-host"
        echo "  export DB_NAME=articonnect"
        echo "  export DB_USER=your-db-user"
        echo "  export DB_PASSWORD=your-db-password"
        echo ""
        echo "Optional variables:"
        echo "  export PGBOUNCER_ADMIN_PASSWORD=admin-password"
        echo "  export PGBOUNCER_STATS_PASSWORD=stats-password"
        exit 1
    fi
}

# Generate userlist.txt from template
generate_userlist() {
    echo "Generating userlist.txt..."

    # Set default passwords if not provided
    PGBOUNCER_ADMIN_PASSWORD="${PGBOUNCER_ADMIN_PASSWORD:-$(openssl rand -base64 16)}"
    PGBOUNCER_STATS_PASSWORD="${PGBOUNCER_STATS_PASSWORD:-$(openssl rand -base64 16)}"

    # Generate MD5 hash for passwords
    db_user_md5="md5$(echo -n "${DB_PASSWORD}${DB_USER}" | md5sum | cut -d' ' -f1)"
    admin_md5="md5$(echo -n "${PGBOUNCER_ADMIN_PASSWORD}admin" | md5sum | cut -d' ' -f1)"
    stats_md5="md5$(echo -n "${PGBOUNCER_STATS_PASSWORD}stats" | md5sum | cut -d' ' -f1)"

    cat > "$SCRIPT_DIR/userlist.txt" << EOF
;; PgBouncer userlist - Generated by setup.sh
;; DO NOT COMMIT THIS FILE TO VERSION CONTROL

"${DB_USER}" "${db_user_md5}"
"admin" "${admin_md5}"
"stats" "${stats_md5}"
EOF

    chmod 600 "$SCRIPT_DIR/userlist.txt"
    echo "userlist.txt generated successfully"

    if [ -z "$PGBOUNCER_ADMIN_PASSWORD_PROVIDED" ]; then
        echo ""
        echo "Generated admin password: $PGBOUNCER_ADMIN_PASSWORD"
        echo "Generated stats password: $PGBOUNCER_STATS_PASSWORD"
        echo "Please save these passwords securely!"
    fi
}

# Start PgBouncer
start_pgbouncer() {
    echo ""
    echo "Starting PgBouncer..."

    cd "$SCRIPT_DIR"
    docker-compose up -d

    echo ""
    echo "PgBouncer started successfully!"
    echo ""
    echo "Connection details:"
    echo "  Host: localhost"
    echo "  Port: ${PGBOUNCER_PORT:-6432}"
    echo "  Database: ${DB_NAME}"
    echo "  User: ${DB_USER}"
    echo ""
    echo "Update your application DATABASE_URL to:"
    echo "  postgresql://${DB_USER}:PASSWORD@localhost:${PGBOUNCER_PORT:-6432}/${DB_NAME}?pgbouncer=true"
    echo ""
    echo "Admin console:"
    echo "  psql -h localhost -p ${PGBOUNCER_PORT:-6432} -U admin pgbouncer"
}

# Stop PgBouncer
stop_pgbouncer() {
    echo "Stopping PgBouncer..."
    cd "$SCRIPT_DIR"
    docker-compose down
    echo "PgBouncer stopped"
}

# Show PgBouncer status
show_status() {
    echo "PgBouncer Status:"
    cd "$SCRIPT_DIR"
    docker-compose ps
    echo ""
    echo "Pool statistics (connect as admin to see full stats):"
    docker-compose exec pgbouncer psql -h localhost -p 6432 -U stats pgbouncer -c "SHOW POOLS;" 2>/dev/null || echo "Could not connect to PgBouncer"
}

# Main script
case "${1:-}" in
    setup)
        check_env_vars
        generate_userlist
        ;;
    start)
        check_env_vars
        [ ! -f "$SCRIPT_DIR/userlist.txt" ] && generate_userlist
        start_pgbouncer
        ;;
    stop)
        stop_pgbouncer
        ;;
    restart)
        stop_pgbouncer
        sleep 2
        check_env_vars
        start_pgbouncer
        ;;
    status)
        show_status
        ;;
    *)
        echo "Usage: $0 {setup|start|stop|restart|status}"
        echo ""
        echo "Commands:"
        echo "  setup   - Generate configuration files"
        echo "  start   - Start PgBouncer"
        echo "  stop    - Stop PgBouncer"
        echo "  restart - Restart PgBouncer"
        echo "  status  - Show PgBouncer status"
        exit 1
        ;;
esac
